apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: qiot-historical-data-
spec:
  params:
  - name: SERVICE_NAME
    value: historical-data-service
  - name: GITHUB_REPO_URL
    value: https://github.com/qiot-project/qiot-datahub-importer.git
  - name: GITHUB_REPO_REVISION
    value: v2
  - name: APP_ENV_VARS
    value: ' -e DBHOST=postgresql -e INFLUXDB_CONNECTION_STRING=http://timeseries-service-influxdb2 -e INFLUXDB_ORG_ID=qiot -e INFLUXDB_DATA_BUCKET_ID=covid19 -e INFLUXDB_DATA_BUCKET_NAME=covid19 -e INFLUXDB_TOKEN=JCNTRpJj6AsvqiD7MnRWPZhIrXYpHwusT_Mwvc0I26E6lFJsXNzkaD2SbkIxeeH3TbiakNbbZGm_EKk8dlCCbQ=='
  - name: CREATE_ROUTE
    value: 'yes'
  - name: BUILD_TYPE
    value: quarkus-fast-jar
  - name: DOCKER_TYPE
    value: fast-jar
  pipelineRef:
    name: quarkus-app-build
  serviceAccountName: pipeline
  timeout: 30m0s
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: historical-data-output
  - configMap:
      name: maven-settings-xml
    name: maven-settings
