---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: qiot-station
spec:
  params:
  - name: SERVICE_NAME
    value: station-service
  - name: GITHUB_REPO_URL
    value: https://github.com/qiot-project/qiot-datahub-station
  - name: GITHUB_REPO_REVISION
    value: main
  - name: APP_ENV_VARS
    value: ' -e DBHOST=postgresql -e LOCALIZATION-SERVICE-URL=http://localization-service:8080'
  - name: CREATE_ROUTE
    value: 'no'
  pipelineRef:
    name: quarkus-app-build
  serviceAccountName: pipeline
  timeout: 30m0s
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: station-output
  - configMap:
      name: maven-settings-xml
    name: maven-settings
